---
title: "R Notebook"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(fig.width=22, fig.height=20) 
library(tidyverse)
library(mgcv)
library(visreg)
```

## Import
Importing Cleaned Data
```{r}
# Read in data
ames = read_csv('./data/train_cleanest.csv')
test = read_csv('./data/test_cleanest.csv')

# Order alphabetically
ames = ames[,order(colnames(ames))]
test= test[,order(colnames(test))]

# Remove artifact features
ames = ames %>% dplyr::select(-X1)
test = test %>% dplyr::select(-X1)

# Rename for R compatability
ames = ames[,order(colnames(ames))] %>% 
  rename('FirstFlrSF' = "1stFlrSF", 'SecFlrSF' = '2ndFlrSF', 'ThreeSeaPorch' = '3SsnPorch')
test = test[,order(colnames(test))] %>% 
  rename('FirstFlrSF' = "1stFlrSF", 'SecFlrSF' = '2ndFlrSF', 'ThreeSeaPorch' = '3SsnPorch')


# Factorize PriceRange feature
ames$PriceRange <- factor(ames$PriceRange, levels = c("High", "Middle", "Low"))
test$PriceRange <- factor(test$PriceRange, levels = c("High", "Middle", "Low"))

# Additional Feature Exploration
ames$QualCond = ames$OverallCond * ames$OverallQual
test$QualCond = test$OverallCond * test$OverallQual

```

## Split into train and validation
```{r}
set.seed(3)
train.idx = sample(1:nrow(ames), 7*nrow(ames)/10)
ames_train = ames[train.idx,]
ames_test = ames[-train.idx,]
```

```{r}
## Base GAM Model
ames.gam.base <- mgcv::gam(logPrice
                ~ s(TotalSF, by=PriceRange)
                + QualCond
                + Fireplaces:PriceRange
                + s(MSSubClass)
                + Neighborhood:PriceRange,
                method='GCV.Cp',
                data=ames_train)
## Base LM Model
ames.lm <- lm(logPrice
              ~ TotalSF:PriceRange
              + QualCond
              + Age
              + Fireplaces:PriceRange
              + MSSubClass
              + Neighborhood:PriceRange
              + GarageArea:GarageCars,
              data=ames_train)

true = ames_test[,'SalePrice'][[1]]

gam.base.predictions = predict.gam(ames.gam.base, newdata = ames_test, type = 'response') #log preds
gam.base.errors = gam.base.predictions - log(true) # residuals
gam.base.diff =exp(gam.base.predictions) - true # $ diff

lm.predictions = predict(ames.lm, newdata = ames_test)
lm.errors = lm.predictions - log(true)
lm.diff = exp(lm.predictions) - true

print(paste('GAM RMSE:',sqrt(mean(gam.base.errors^2))))
print(paste('LM RMSE:',sqrt(mean(lm.errors^2))))

print(paste('GAM: Error in $ as Predicted:',round(mean(abs(gam.base.diff)),2)))
print(paste('LM: Error in $ as Predicted:',round(mean(abs(lm.diff)),2)))

summary(ames.gam.base)
plot(ames.gam.base)
```

```{r}

ames$PriceRange <- factor(ames$PriceRange, levels = c("Low", "Middle", "High"))

ames.gam.test = mgcv::gam(logPrice ~
                            s(OverallQual, by=PriceRange, bs='gp')
                          + s(TotalSF, by=PriceRange, bs='gp'),
                          method='ML',
                          data=ames)

test.preds= test %>% mutate(logPrice = predict.gam(ames.gam.test, newdata = test, type = 'response'))

gam_qual_eda = visreg(ames.gam.test, 'OverallQual', partial=TRUE,

       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.4, col='black')) + 
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Overall Quality') +
  geom_smooth(method='lm', color='blue') +
  scale_color_manual(values=colors)

ggsave(paste0("./presentation/gam_qual_eda.png"), gam_qual_eda)

gam_qual_edaP = visreg(ames.gam.test, 'OverallQual', by='PriceRange', partial=TRUE,

       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.4, col='black')) + 
  ylim(10,15) +
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Overall Quality') +
  scale_color_manual(values=colors)

ggsave(paste0("./presentation/gam_qual_edaP.png"), gam_qual_edaP)

visreg(ames.gam.test, 'TotalSF', partial=TRUE,

       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.4, col='black')) + 
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Total Home SF') +
  geom_smooth(method='lm', color='blue') +
  scale_color_manual(values=colors)


visreg(ames.gam.test, 'TotalSF', by='PriceRange', partial=TRUE,

       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.4, col='black')) + 
  ylim(10,15) +
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Total Home SF') +
  scale_color_manual(values=colors)
```


```{r}

grliv = visreg(ames.gam.base, 'TotalSF', partial=TRUE,

       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.4, col='black')) + 
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Total Home SF') +
  geom_smooth(method='lm', color='blue') +
  scale_color_manual(values=colors)

ggsave(paste0("./presentation/gam_grliv.png"), grliv)

grliv_price = visreg(ames.gam.base, 'TotalSF', by='PriceRange', partial=TRUE,

       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.4, col='black')) + 
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Total Home SF') +
  scale_color_manual(values=colors)


ggsave(paste0("./presentation/gam_grliv_price.png"), grliv_price)

msub = visreg(ames.gam.base, 'MSSubClass', partial=TRUE,
              jitter=TRUE,
              alpha=0.05, gg=TRUE, 
              line=list(col="red"),
              fill=list(fill="pink"),
              points=list(size=1, pch=1, alpha=0.2, col='black')) + 
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'MSSubClass: Type of Dwelling') +
  geom_smooth(method='lm', color='blue') +
  scale_color_manual(values=colors)

ggsave(paste0("./presentation/gam_msub.png"), msub)

garage = visreg(ames.gam.base, 'GarageArea', by='GarageCars', partial=TRUE,
       #scale='response',
       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
              jitter=TRUE,
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.2, col='black')) + 
  geom_smooth(method='lm', color='blue') +
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Garage Area')

ggsave(paste0("./presentation/gam_garage.png"), garage)

age = visreg(ames.gam.base, 'Age', partial=TRUE,
       #scale='response',
       alpha=0.05, gg=TRUE, 
       line=list(col="red"),
       fill=list(fill="pink"),
       points=list(size=1, pch=1, alpha=0.2, col='black')) + 
  theme_bw() +
  labs(y = 'Log Sale Price', x = 'Age of Home') +
  geom_smooth(method='lm', color='blue') +
  scale_color_manual(values=colors)

ggsave(paste0("./presentation/gam_age.png"), age)
```

```{r}

## Testing Model Assumptions

gam.anal= tibble(data.frame(cbind(ames.gam.base$fitted.values, ames$logPrice, ames.gam.base$residuals)))
colnames(gam.anal) = c('Fitted','Real', 'Error')

gam.anal = gam.anal %>% mutate(PriceRange = ames$PriceRange)
gam.anal$PriceRange <- factor(gam.anal$PriceRange, levels = c("High", "Middle", "Low"))

gam.anal$stdError = ames.gam.base$residuals/sd(ames.gam.base$residuals)

gam.anal$resSize = gam.anal$stdError
  
gam_res_fitted = 
  gam.anal %>% 
  ggplot(aes(x = Fitted, y = stdError)) +
  geom_point(alpha=0.7,aes(color = PriceRange, size = pi*resSize^4)) +
  geom_hline(yintercept=qt(0.025, df = nrow(gam.anal) - 2), color = "black", linetype="dashed", color = "red") +
  geom_hline(yintercept=qt(1 - 0.025, df = nrow(gam.anal) - 2), color = "black", linetype="dashed", color = "red") +
  labs(x = 'Fitted Values', y = 'GAM Standardized Residuals') +
  ylim(-7,5) +
  guides(size = FALSE) +  # Size legend also removed
  theme_bw()


ggsave(paste0("./presentation/preds_gam/gam_res_fitted.png"), gam_res_fitted)
  
gam_pred_v_true = 
  gam.anal %>% 
  ggplot(aes(x = Real, y = Fitted, col = PriceRange)) +
  geom_point(alpha=0.5) +
  geom_abline(intercept = 0, slope = 1, linetype = 'dashed', color = 'red') +
  theme_bw() +
  labs(x = 'Log Price', y = 'GAM Prediction')


ggsave(paste0("./presentation/preds_gam/gam_pred_v_true.png"), gam_pred_v_true)
  
lm.anal= tibble(data.frame(cbind(ames.lm$fitted.values, ames$logPrice, ames.lm$residuals)))
colnames(lm.anal) = c('Fitted','Real','Error')
lm.anal$stdError = ames.lm$residuals/sd(ames.lm$residuals)


lm.anal$resSize = lm.anal$stdError
lm.anal$index = 1:nrow(lm.anal)
lm.anal = lm.anal %>% mutate(PriceRange = ames$PriceRange)
lm.anal$PriceRange <- factor(lm.anal$PriceRange, levels = c("High", "Middle", "Low"))


lm_res_fitted = lm.anal %>% 
  ggplot(aes(x = Fitted, y = stdError, col=PriceRange)) +
  geom_point(alpha=0.7, aes(color = PriceRange, size = pi*resSize^4)) +
  geom_hline(yintercept=qt(0.025, df = nrow(gam.anal) - 2), color = "black", linetype="dashed", color = "red") +
  geom_hline(yintercept=qt(1 - 0.025, df = nrow(gam.anal) - 2), color = "black", linetype="dashed", color = "red") +
  labs(x = 'Fitted Values', y = 'LM Standardized Residuals') +
  guides(size = FALSE) +  # Size legend also removed
  ylim(-7,5) +
  theme_bw()


ggsave(paste0("./presentation/preds_lm/lm_res_fitted.png"), lm_res_fitted)

lm_pred_v_true = 
  lm.anal %>% 
  ggplot(aes(x = Real, y = Fitted, col=PriceRange)) +
  geom_point(alpha=0.5) +
  geom_abline(intercept = 0, slope = 1, linetype = 'dashed', color = 'red') +
  theme_bw() +
  labs(x = 'Log Price', y = 'LM Prediction')
  
ggsave(paste0("./presentation/preds_lm/lm_pred_v_true.png"), lm_pred_v_true)
```


```{r}
ames.gam <- mgcv::gam(log(SalePrice)
                ~ s(GrLivArea, by=PriceRange, bs='cs', id=1)
                + s(YearBuilt)
                + ti(OverallQual,OverallCond)
                + s(MSSubClass)
                + s(YearBuilt)
                + CentralAir
                ,method='GCV.Cp', data=ames_train, gamma=1.4, select=TRUE)

visreg(ames.gam)

true = ames_test[,'SalePrice'][[1]]

gam.predictions = predict.gam(ames.gam, newdata = ames_test, type = 'response')
gam.errors = gam.predictions - log(true)
gam.diff =exp(gam.predictions) - true

plot(density(gam.errors), col ='red')
lines(density(gam.base.errors), col='black', lty=2)
legend("topright",legend=c('GAM Residuals','Base GAM Residuals'),
       col=c("red","black"), lty=1:2, cex=0.8)


print(paste('GAM RMSE:',sqrt(mean(gam.errors^2))))

print(paste('GAM: Error in $ as Predicted:',round(mean(abs(gam.diff)),2)))

plot(true, exp(gam.predictions), ylim=c(0,7e5), xlim=c(0,7e5))
abline(a=0,b=1)

summary(ames.gam)
```

### Submissions
```{r}
gam.test_predictions = predict.gam(ames.gam.base, newdata = test, type = 'response')
submission = data.frame(exp(gam.test_predictions))
colnames(submission) = 'SalePrice'
submission = tibble::rowid_to_column(submission,'Id')
rownames(submission) = 1461:(nrow(submission)+1460)
gmb_submission = mutate(submission, Id = Id + 1460)

lm.test_predictions = predict(ames.lm, newdata = test, type = 'response')
lm_submission = data.frame(exp(lm.test_predictions))
colnames(lm_submission) = 'SalePrice'
lm_submission = tibble::rowid_to_column(lm_submission,'Id')
rownames(lm_submission) = 1461:(nrow(lm_submission)+1460)
lm_submission = mutate(lm_submission, Id = Id + 1460)
```


```{r}
# write.table(lm_submission,file="./data/lm_predictions.csv",col.names = c("Id","SalePrice"),sep = ",",row.names = F)
# write.table(gmb_submission,file="./data/gmb_predictions.csv",col.names = c("Id","SalePrice"),sep = ",",row.names = F)
# 
# write.table((lm_submission+gmb_submission)/2,file="./data/avg_predictions.csv",col.names = c("Id","SalePrice"),sep = ",",row.names = F)
```
